[project]
name = "projectcordelia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=6.0.0",
    "streamlit>=1.47.0",
]
